form_mapping = {
    "surname": "ctl00_SiteContentPlaceHolder_FormView1_tbxAPP_SURNAME",
    "given_name": "ctl00_SiteContentPlaceHolder_FormView1_tbxAPP_GIVEN_NAME",
    "full_name_native_alphabet": "ctl00_SiteContentPlaceHolder_FormView1_tbxAPP_FULL_NAME_NATIVE",
    "full_name_native_alphabet_na": "ctl00_SiteContentPlaceHolder_FormView1_cbexAPP_FULL_NAME_NATIVE_NA",
    "sex": "ctl00_SiteContentPlaceHolder_FormView1_ddlAPP_GENDER",
    "marital_status": "ctl00_SiteContentPlaceHolder_FormView1_ddlAPP_MARITAL_STATUS",
    "has_other_names_used": "ctl00_SiteContentPlaceHolder_FormView1_rblOtherNames",
    "other_names.surname": "ctl00_SiteContentPlaceHolder_FormView1_DListAlias_ctl00_tbxSURNAME",
    "other_names.givenname": "ctl00_SiteContentPlaceHolder_FormView1_DListAlias_ctl00_tbxGIVEN_NAME",
    "other_names.add_group": "ctl00_SiteContentPlaceHolder_FormView1_DListAlias_ctl00_InsertButtonAlias",
    "other_names.remove_group": "ctl00_SiteContentPlaceHolder_FormView1_DListAlias_ctl00_DeleteButtonAlias",
    "has_telecode": "ctl00_SiteContentPlaceHolder_FormView1_rblTelecodeQuestion",
    "telecode_surname": "ctl00_SiteContentPlaceHolder_FormView1_tbxAPP_TelecodeSURNAME",
    "telecode_given": "ctl00_SiteContentPlaceHolder_FormView1_tbxAPP_TelecodeGIVEN_NAME",
    "birth_date_dd": "ctl00_SiteContentPlaceHolder_FormView1_ddlDOBDay",
    "birth_date_mm": "ctl00_SiteContentPlaceHolder_FormView1_ddlDOBMonth", 
    "birth_date_yyyy": "ctl00_SiteContentPlaceHolder_FormView1_tbxDOBYear",
    "birth_city": "ctl00_SiteContentPlaceHolder_FormView1_tbxAPP_POB_CITY",
    "birth_state_province": "ctl00_SiteContentPlaceHolder_FormView1_tbxAPP_POB_ST_PROVINCE",
    "birth_state_province_na": "ctl00_SiteContentPlaceHolder_FormView1_cbexAPP_POB_ST_PROVINCE_NA",
    "birth_country": "ctl00_SiteContentPlaceHolder_FormView1_ddlAPP_POB_CNTRY"
} 