export const countryList = [
    "Afghanistan (AFG)",
    "Aland Islands (ALA)",
    "Albania (ALB)",
    "Algeria (DZA)",
    "American Samoa (ASM)",
    "Andorra (AND)",
    "Angola (AGO)",
    "Anguilla (AIA)",
    "Antarctica (ATA)",
    "Antigua and Barbuda (ATG)",
    "Argentina (ARG)",
    "Armenia (ARM)",
    "Aruba (ABW)",
    "Australia (AUS)",
    "Austria (AUT)",
    "Azerbaijan (AZE)",
    "Bahamas, The (BHS)",
    "Bahrain (BHR)",
    "Bangladesh (BGD)",
    "Barbados (BRB)",
    "Belarus (BLR)",
    "Bermuda (BMU)",
    "Bhutan (BTN)",
    "Bolivia (BOL)",
    "Bonaire, Sint Eustatius, and Saba (BES)",
    "Bosnia and Herzegovina (BIH)",
    "Botswana (BWA)",
    "Bouvet Island (BVT)",
    "Brazil (BRA)",
    "British Indian Ocean Territory (IOT)",
    "British Virgin Islands (VGB)",
    "Bulgaria (BGR)",
    "Burkina Faso (BFA)",
    "Burma (Myanmar) (MMR)",
    "Cambodia (KHM)",
    "Cameroon (CMR)",
    "Canada (CAN)",
    "Cape Verde (CPV)",
    "Cayman Islands (CYM)",
    "Central African Republic (CAF)",
    "Chad (TCD)",
    "China (CHN)",
    "Christmas Island (CXR)",
    "Cocos (Keeling) Islands (CCK)",
    "Colombia (COL)",
    "Congo, Democratic Republic of the (COD)",
    "Cook Islands (COK)",
    "Costa Rica (CRI)",
    "Croatia (HRV)",
    "Cuba (CUB)",
    "Curacao (CUW)",
    "Denmark (DNK)",
    "Dominica (DMA)",
    "Dominican Republic (DOM)",
    "Ecuador (ECU)",
    "El Salvador (SLV)",
    "Equatorial Guinea (GNQ)",
    "Eritrea (ERI)",
    "Estonia (EST)",
    "Eswatini (SWZ)",
    "Ethiopia (ETH)",
    "European Union Lassier Passier (EUE)",
    "Falkland Islands (Islas Malvinas) (FLK)",
    "Faroe Islands (FRO)",
    "Finland (FIN)",
    "France (FRA)",
    "French Guiana (GUF)",
    "French Polynesia (PYF)",
    "Gabon (GAB)",
    "Gambia, The (GMB)",
    "Georgia (GEO)",
    "Germany (DEU)",
    "Germany (East) Democratic Republic (DDR)",
    "Ghana (GHA)",
    "Gibraltar (GIB)",
    "Greenland (GRL)",
    "Grenada (GRD)",
    "Guadeloupe (GLP)",
    "Guam (GUM)",
    "Guatemala (GTM)",
    "Guinea (GIN)",
    "Guinea-Bissau (GNB)",
    "Guyana (GUY)",
    "Haiti (HTI)",
    "Heard Island and McDonald Islands (HMD)",
    "Holy See (Vatican City) (VAT)",
    "Honduras (HND)",
    "Hungary (HUN)",
    "Iceland (ISL)",
    "India (IND)",
    "Indonesia (IDN)",
    "Iran (IRN)",
    "Iraq (IRQ)",
    "Ireland (IRL)",
    "Isle of Man (IMN)",
    "Israel (ISR)",
    "Italy (ITA)",
    "Jamaica (JAM)",
    "Japan (JPN)",
    "Jordan (JOR)",
    "Kazakhstan (KAZ)",
    "Kenya (KEN)",
    "Kiribati (KIR)",
    "Korea, North (PRK)",
    "Korea, South (KOR)",
    "Kuwait (KWT)",
    "Kyrgyzstan (KGZ)",
    "Laos (LAO)",
    "Latvia (LVA)",
    "Lebanon (LBN)",
    "Liberia (LBR)",
    "Libya (LBY)",
    "Lithuania (LTU)",
    "Macau (MAC)",
    "Macedonia (MKD)",
    "Madagascar (MDG)",
    "Malawi (MWI)",
    "Malaysia (MYS)",
    "Maldives (MDV)",
    "Mali (MLI)",
    "Malta (MLT)",
    "Marshall Islands (MHL)",
    "Martinique (MTQ)",
    "Mauritania (MRT)",
    "Mauritius (MUS)",
    "Mayotte (MYT)",
    "Micronesia, Federated States of (FSM)",
    "Moldova (MDA)",
    "Monaco (MCO)",
    "Mongolia (MNG)",
    "Montserrat (MSR)",
    "Morocco (MAR)",
    "Mozambique (MOZ)",
    "Namibia (NAM)",
    "Nauru (NRU)",
    "Nepal (NPL)",
    "Netherlands (NLD)",
    "Netherlands Antilles (ANT)",
    "Neutral Zone (S. Arabia/Iraq) (NTZ)",
    "New Caledonia (NCL)",
    "New Zealand (NZL)",
    "Nicaragua (NIC)",
    "Nigeria (NGA)",
    "Norfolk Island (NFK)",
    "Northern Mariana Islands (MNP)",
    "Norway (NOR)",
    "Oman (OMN)",
    "Pakistan (PAK)",
    "Palau (PLW)",
    "Palestine (PSE)",
    "Panama (PAN)",
    "Papua New Guinea (PNG)",
    "Paraguay (PRY)",
    "Pitcairn Islands (PCN)",
    "Poland (POL)",
    "Portugal (PRT)",
    "Qatar (QAT)",
    "Romania (ROU)",
    "Russia (RUS)",
    "Rwanda (RWA)",
    "Saint Barthelemy (BLM)",
    "Saint Helena (SHN)",
    "Saint Kitts and Nevis (KNA)",
    "Saint Lucia (LCA)",
    "Saint Martin (MAF)",
    "Saint Pierre and Miquelon (SPM)",
    "Saint Vincent and the Grenadines (VCT)",
    "Samoa (WSM)",
    "San Marino (SMR)",
    "Sao Tome and Principe (STP)",
    "Saudi Arabia (SAU)",
    "Senegal (SEN)",
    "Serbia (SRB)",
    "Sierra Leone (SLE)",
    "Singapore (SGP)",
    "Sint Maarten (SXM)",
    "Slovakia (SVK)",
    "Slovenia (SVN)",
    "Solomon Islands (SLB)",
    "Somalia (SOM)",
    "South Africa (ZAF)",
    "South Georgia and the South Sandwich Islands (SGS)",
    "South Sudan (SSD)",
    "Spain (ESP)",
    "Sri Lanka (LKA)",
    "Sudan (SDN)",
    "Suriname (SUR)",
    "Svalbard (SJM)",
    "Switzerland (CHE)",
    "Syria (SYR)",
    "Taiwan (TWN)",
    "Tajikistan (TJK)",
    "Tanzania (TZA)",
    "Thailand (THA)",
    "Tokelau (TKL)",
    "Tonga (TON)",
    "Trinidad and Tobago (TTO)",
    "Tunisia (TUN)",
    "Turkmenistan (TKM)",
    "Turks and Caicos Islands (TCA)",
    "Tuvalu (TUV)",
    "Uganda (UGA)",
    "Ukraine (UKR)",
    "United Arab Emirates (ARE)",
    "United Kingdom - British National (Overseas) (GBN)",
    "United Kingdom - British Overseas Citizen (GBO)",
    "United Kingdom - British Overseas Territories Citizen (GBD)",
    "United States (USA)",
    "United States Minor Outlying Islands (UMI)",
    "Uruguay (URY)",
    "Uzbekistan (UZB)",
    "Vanuatu (VUT)",
    "Venezuela (VEN)",
    "Vietnam (VNM)",
    "Virgin Islands (VIR)",
    "Wallis and Futuna (WLF)",
    "Western Sahara (ESH)",
    "Zambia (ZMB)",
    "Zimbabwe (ZWE)"
]